---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telemetry.podbeacon.io
  resources:
  - telemetryprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.podbeacon.io
  resources:
  - telemetryprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - telemetry.podbeacon.io
  resources:
  - telemetryprofiles/status
  verbs:
  - get
  - patch
  - update
