apiVersion: telemetry.podbeacon.io/v1alpha1
kind: TelemetryProfile
metadata:
  labels:
    app.kubernetes.io/name: podbeacon
    app.kubernetes.io/managed-by: kustomize
  name: telemetryprofile-sample
spec:
  exporter:
    endpoint: "otel-collector.monitoring.svc.cluster.local:4317"
    tls:
      insecure: true
  signals:
  - traces
  - metrics
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
